[Settings]
ID = "1681c84f-e32f-490b-8951-9570997ad8dc"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "instagram/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "instagram/build/"
  # This will be your default build command
  command = "yarn build"