
[Settings]
ID = "d0b5f31d-733b-471c-a2b4-7696c4e7f467"


# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "real-instagram-clone/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "real-instagram-clone/build/"
  # This will be your default build command
  command = "yarn build"